"""cadastro

Revision ID: 00ac13d41094
Revises: 8499b637ccf2
Create Date: 2024-06-15 10:32:51.483868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ac13d41094'
down_revision = '8499b637ccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('um_visual', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('codigo_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ncm', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('familia', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.drop_column('familia')
        batch_op.drop_column('ncm')
        batch_op.drop_column('codigo_cliente')
        batch_op.drop_column('um_visual')

    # ### end Alembic commands ###
