"""pack rel14

Revision ID: 094972a65df1
Revises: 426529989266
Create Date: 2024-06-09 14:44:16.662358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094972a65df1'
down_revision = '426529989266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packlist',
    sa.Column('packlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('peso_liquido', sa.Integer(), nullable=False),
    sa.Column('peso_bruto', sa.Integer(), nullable=False),
    sa.Column('embalagem', sa.String(length=250), nullable=True),
    sa.Column('obs_entrega', sa.String(length=255), nullable=True),
    sa.Column('obs', sa.String(length=255), nullable=True),
    sa.Column('status2', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('packlist_id')
    )
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packlist', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('packlist')

    op.drop_table('packlist')
    # ### end Alembic commands ###
