"""operador-lote-visual

Revision ID: 37edad79c6e0
Revises: 59482d461115
Create Date: 2024-06-16 09:29:05.998085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37edad79c6e0'
down_revision = '59482d461115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_visual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_visual', schema=None) as batch_op:
        batch_op.drop_column('operador')

    # ### end Alembic commands ###
