"""empty message

Revision ID: 426529989266
Revises: 5ba14687de83
Create Date: 2024-06-09 14:02:14.612649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426529989266'
down_revision = '5ba14687de83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packlist')
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('packlist')
        batch_op.drop_column('packlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packlist_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('packlist', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('packlist',
    sa.Column('Packlist', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('peso_liquido', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso_bruto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embalagem', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('obs_entrega', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('obs', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.CHAR(length=1), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('Packlist'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
