"""operador-lote

Revision ID: 59482d461115
Revises: 9d381eb7aa7b
Create Date: 2024-06-16 09:23:18.298445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59482d461115'
down_revision = '9d381eb7aa7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_mov_op', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operador', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_mov_op', schema=None) as batch_op:
        batch_op.drop_column('operador')

    # ### end Alembic commands ###
