"""packlist2

Revision ID: 5ba14687de83
Revises: b8209c7f6a17
Create Date: 2024-06-07 02:29:29.639982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ba14687de83'
down_revision = 'b8209c7f6a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packlist', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_column('Packlist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Packlist', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('packlist')

    # ### end Alembic commands ###
