"""migração MOV LOTE REF STR

Revision ID: 6311dbf4376f
Revises: df22a55487a9
Create Date: 2024-05-13 11:52:01.265596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6311dbf4376f'
down_revision = 'df22a55487a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movimentos_estoque', schema=None) as batch_op:
        batch_op.alter_column('referencia',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movimentos_estoque', schema=None) as batch_op:
        batch_op.alter_column('referencia',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
