"""PEDIDO STRING

Revision ID: 69b7204302d4
Revises: 6c03c4a2d591
Create Date: 2024-05-28 00:24:24.155061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b7204302d4'
down_revision = '6c03c4a2d591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('pedido',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('pedido',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
