"""ferramentas

Revision ID: 6c03c4a2d591
Revises: 6311dbf4376f
Create Date: 2024-05-23 01:07:55.952983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c03c4a2d591'
down_revision = '6311dbf4376f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferramentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimensional', sa.String(length=250), nullable=True))
        batch_op.drop_index('dimencional')
        batch_op.create_unique_constraint(None, ['dimensional'])
        batch_op.drop_column('dimencional')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ferramentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dimencional', mysql.VARCHAR(length=250), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('dimencional', ['dimencional'], unique=False)
        batch_op.drop_column('dimensional')

    # ### end Alembic commands ###
