"""id_produto

Revision ID: 7f3706a3558a
Revises: 094972a65df1
Create Date: 2024-06-13 18:09:26.289106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3706a3558a'
down_revision = '094972a65df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_produto', sa.Integer(), nullable=True))

    with op.batch_alter_table('ops_visual', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['numero_op_visual'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ops_visual', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.drop_column('id_produto')

    # ### end Alembic commands ###
