"""teste de migraçãoo

Revision ID: 81a97040d46e
Revises: 
Create Date: 2024-05-10 12:06:30.843164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81a97040d46e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.alter_column('material',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('peso_material',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('dimencional_real',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('obs',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('canto',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('furo',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('embalagem',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('status2',
               existing_type=mysql.CHAR(length=1),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.create_unique_constraint(None, ['pedido'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status2',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=1),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('embalagem',
               existing_type=sa.String(length=250),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('furo',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=1),
               existing_nullable=True)
        batch_op.alter_column('canto',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=1),
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('obs',
               existing_type=sa.String(length=250),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dimencional_real',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('peso_material',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('material',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
