"""id_produto2

Revision ID: 8499b637ccf2
Revises: 7f3706a3558a
Create Date: 2024-06-13 20:43:32.655759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8499b637ccf2'
down_revision = '7f3706a3558a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.alter_column('id_produto',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.alter_column('id_produto',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
