"""fam ope set

Revision ID: 8f40cbb1e9ca
Revises: 00ac13d41094
Create Date: 2024-06-15 14:03:45.079298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f40cbb1e9ca'
down_revision = '00ac13d41094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('familia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('familia', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('familia')
    )
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['item'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cadastro_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('familia')
    # ### end Alembic commands ###
