"""id_lotel

Revision ID: 9185bf0372fc
Revises: 37edad79c6e0
Create Date: 2024-06-17 17:05:32.718362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9185bf0372fc'
down_revision = '37edad79c6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_mov_op', schema=None) as batch_op:
        batch_op.alter_column('id_lote',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes_mov_op', schema=None) as batch_op:
        batch_op.alter_column('id_lote',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
