"""migração pedido não unico

Revision ID: 99f12b53e02e
Revises: 81a97040d46e
Create Date: 2024-05-13 11:34:35.896710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f12b53e02e'
down_revision = '81a97040d46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_index('pedido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_index('pedido', ['pedido'], unique=False)

    # ### end Alembic commands ###
