"""packlisto

Revision ID: b8209c7f6a17
Revises: 69b7204302d4
Create Date: 2024-06-06 19:00:56.342078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8209c7f6a17'
down_revision = '69b7204302d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packlist', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qtd_faturada', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('qtd_faturada')
        batch_op.drop_column('packlist')

    # ### end Alembic commands ###
