"""migração LOTE REF STR

Revision ID: df22a55487a9
Revises: 99f12b53e02e
Create Date: 2024-05-13 11:48:31.301495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df22a55487a9'
down_revision = '99f12b53e02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_visual', schema=None) as batch_op:
        batch_op.alter_column('referencia',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote_visual', schema=None) as batch_op:
        batch_op.alter_column('referencia',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
